# Generated by Django 2.1.3 on 2020-03-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapDjangoApp', '0002_auto_20200322_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetails',
            old_name='Catagory',
            new_name='Category',
        ),
    ]
